name = "DN1"
uuid = "3c154e24-bdbd-4a27-bc81-0b94681cdaf5"
authors = ["TineCrnugelj <tine.crnugelj@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
